
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v4
      with:
        subdirectory: Task8_testing

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
    - name: Display go version
      run: go version
    
    - name: Print working directory
      run: pwd
      working-directory: Task8_testing

    - name: Go mod tidy
      run: go mod tidy
      working-directory: Task8_testing

    - name: Test
      run: go test ./... -v
      working-directory: Task8_testing

    - name: Generate coverage report
      run: go test ./... -coverprofile=coverage.out
      working-directory: Task8_testing

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.out
